POST {{baseURL}}/admins
Content-Type: application/json

{
    "firstName": "Alaa",
    "lastName": "Haddabeh",
    "username": "ahaddabeh",
    "password": "alaaIsHandsome123"
}

###

POST {{baseURL}}/admins/login
Content-Type: application/json

{
    "username": "ahaddabeh",
    "password": "alaaIsHandsome123"
}