POST {{baseURL}}/cart/checkout
Content-Type: application/json

{
    "customer": {
        "name": "Ahmad Haddabeh",
        "email": "testing@example.com"
    },
    "paymentMethod": {
        "card": {
            "number": "4242424242424242",
            "exp_month": 2,
            "exp_year": 2022,
            "cvc": "314"
        }
    },
    "cartItems": [
        {
            "id": 4,
            "price": 12.00,
            "name": "MidSummer's Night",
            "quantity": 1
        },
        {
            "id": 5,
            "price": 15.00,
            "name": "Pink Sands",
            "quantity": 2
        }
    ]
}