POST {{baseURL}}/admins/login
Content-Type: application/json

{
    "username": "{{username}}",
    "password": "{{password}}"
}

###

GET {{baseURL}}/customers/3
Authorization: Bearer {{token}}

###

GET {{baseURL}}/customers?page=1&size=5
Authorization: Bearer {{token}}
