GET {{baseURL}}/orders?page=1&size=5
# Authorization: Bearer
###

GET {{baseURL}}/orders/3
# Authorization: Bearer 

###

POST {{baseURL}}/admins/login
Content-Type: application/json

{
    "username": "ahaddabeh",
    "password": "alaaIsHandsome123"
}